export const GET_PENDING_TEACHERS_REQUEST = "GET_PENDING_TEACHERS_REQUEST";
export const GET_PENDING_TEACHERS_SUCCESS = "GET_PENDING_TEACHERS_SUCCESS";
export const GET_PENDING_TEACHERS_FAIL = "GET_PENDING_TEACHERS_FAIL";

export const REGISTER_ADMIN_REQUEST = "REGISTER_ADMIN_REQUEST";
export const REGISTER_ADMIN_SUCCESS = "REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_FAIL = "REGISTER_ADMIN_FAIL";

export const GET_PENDING_CLASSES_REQUEST = "GET_PENDING_CLASSES_REQUEST";
export const GET_PENDING_CLASSES_SUCCESS = "GET_PENDING_CLASSES_SUCCESS";
export const GET_PENDING_CLASSES_FAIL = "GET_PENDING_CLASSES_FAIL";
