export const GET_PENDING_TEACHERS_REQUEST = "GET_PENDING_TEACHERS_REQUEST";
export const GET_PENDING_TEACHERS_SUCCESS = "GET_PENDING_TEACHERS_SUCCESS";
export const GET_PENDING_TEACHERS_FAIL = "GET_PENDING_TEACHERS_FAIL";
