export const REQUEST_REGISTER_STUDENT = "REQUEST_REGISTER_STUDENT";
export const SUCCESS_REGISTER_STUDENT = "SUCCESS_REGISTER_STUDENT";
export const FAIL_REGISTER_STUDENT = "FAIL_REGISTER_STUDENT";

export const REQUEST_LOGIN_STUDENT = "REQUEST_LOGIN_STUDENT";
export const SUCCESS_LOGIN_STUDENT = "SUCCESS_LOGIN_STUDENT";
export const FAIL_LOGIN_STUDENT = "FAIL_LOGIN_STUDENT";

export const REQUEST_REGISTER_TEACHER = "REQUEST_REGISTER_TEACHER";
export const SUCCESS_REGISTER_TEACHER = "SUCCESS_REGISTER_TEACHER";
export const FAIL_REGISTER_TEACHER = "FAIL_REGISTER_TEACHER";
