export const REQUEST_CLASSID = "REQUEST_CLASSID";
export const SUCCESS_CLASSID = "SUCCESS_CLASSID";
export const FAIL_CLASSID = "FAIL_CLASSID";

export const GET_NOTES_REQUEST = "GET_NOTES_REQUEST";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAIL = "GET_NOTES_FAIL";

export const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST";
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_FAIL = "GET_VIDEOS_FAIL";

export const GET_TEST_REQUEST = "GET_TEST_REQUEST";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";
export const GET_TEST_FAIL = "GET_TEST_FAIL";

export const GET_ANNOUNCEMENTS_REQUEST = "GET_ANNOUNCEMENTS_REQUEST";
export const GET_ANNOUNCEMENTS_SUCCESS = "GET_ANNOUNCEMENTS_SUCCESS";
export const GET_ANNOUNCEMENTS_FAIL = "GET_ANNOUNCEMENTS_FAIL";

export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL";

export const GET_SINGLE_TEST_REQUEST = "GET_SINGLE_TEST_REQUEST";
export const GET_SINGLE_TEST_SUCCESS = "GET_SINGLE_TEST_SUCCESS";
export const GET_SINGLE_TEST_FAIL = "GET_SINGLE_TEST_FAIL";

export const CREATE_ANSWERS_REQUEST = "CREATE_ANSWERS_REQUEST";
export const CREATE_ANSWERS_SUCCESS = "CREATE_ANSWERS_SUCCESS";
export const CREATE_ANSWERS_FAIL = "CREATE_ANSWERS_FAIL";

export const GET_STUDENT_TEST_REQUEST = "GET_STUDENT_TEST_REQUEST";
export const GET_STUDENT_TEST_SUCCESS = "GET_STUDENT_TEST_SUCCESS";
export const GET_STUDENT_TEST_FAIL = "GET_STUDENT_TEST_FAIL";

export const UPLOAD_TOT_MARKS_REQUEST = "UPLOAD_TOT_MARKS_REQUEST";
export const UPLOAD_TOT_MARKS_SUCCESS = "UPLOAD_TOT_MARKS_SUCCESS";
export const UPLOAD_TOT_MARKS_FAIL = "UPLOAD_TOT_MARKS_FAIL";

export const GET_ALL_TEST_MARKS_REQUEST = "GET_ALL_TEST_MARKS_REQUEST";
export const GET_ALL_TEST_MARKS_SUCCESS = "GET_ALL_TEST_MARKS_SUCCESS";
export const GET_ALL_TEST_MARKS_FAIL = "GET_ALL_TEST_MARKS_FAIL";
