export const GET_JOB_REQUEST = "GET_JOB_REQUEST";
export const GET_JOB_SUCCESS = "GET_JOB_SUCCESS";
export const GET_JOB_FAIL = "GET_JOB_FAIL";

export const GET_SCHOLARSHIP_REQUEST = "GET_SCHOLARSHIP_REQUEST";
export const GET_SCHOLARSHIP_SUCCESS = "GET_SCHOLARSHIP_SUCCESS";
export const GET_SCHOLARSHIP_FAIL = "GET_SCHOLARSHIP_FAIL";
