export const GET_ALL_BOOKS_REQUEST = "GET_ALL_BOOKS_REQUEST";
export const GET_ALL_BOOKS_SUCCESS = "GET_ALL_BOOKS_SUCCESS";
export const GET_ALL_BOOKS_FAIL = "GET_ALL_BOOKS_FAIL";

export const GET_ALL_AUDIOBOOKS_REQUEST = "GET_ALL_AUDIOBOOKS_REQUEST";
export const GET_ALL_AUDIOBOOKS_SUCCESS = "GET_ALL_AUDIOBOOKS_SUCCESS";
export const GET_ALL_AUDIOBOOKS_FAIL = "GET_ALL_AUDIOBOOKS_FAIL";

export const GET_ALL_AUTHORS_REQUEST = "GET_ALL_AUTHORS_REQUEST";
export const GET_ALL_AUTHORS_SUCCESS = "GET_ALL_AUTHORS_SUCCESS";
export const GET_ALL_AUTHORS_FAIL = "GET_ALL_AUTHORS_FAIL";
