export const GET_TEACHER_REQUEST = "GET_TEACHER_REQUEST";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
export const GET_TEACHER_FAIL = "GET_TEACHER_FAIL";

export const GET_ENROLLED_CLASSES_REQUEST = "GET_ENROLLED_CLASSES_REQUEST";
export const GET_ENROLLED_CLASSES_SUCCESS = "GET_ENROLLED_CLASSES_SUCCESS";
export const GET_ENROLLED_CLASSES_FAIL = "GET_ENROLLED_CLASSES_FAIL";

export const CREATE_ANNOUNCEMENT_REQUEST = "CREATE_ANNOUNCEMENT_REQUEST";
export const CREATE_ANNOUNCEMENT_SUCCESS = "CREATE_ANNOUNCEMENT_SUCCESS";
export const CREATE_ANNOUNCEMENT_FAIL = "CREATE_ANNOUNCEMENT_FAIL";

export const CREATE_NOTES_REQUEST = "CREATE_NOTES_REQUEST";
export const CREATE_NOTES_SUCCESS = "CREATE_NOTES_SUCCESS";
export const CREATE_NOTES_FAIL = "CREATE_NOTES_FAIL";

export const CREATE_VIDEOS_REQUEST = "CREATE_VIDEOS_REQUEST";
export const CREATE_VIDEOS_SUCCESS = "CREATE_VIDEOS_SUCCESS";
export const CREATE_VIDEOS_FAIL = "CREATE_VIDEOS_FAIL";

export const CREATE_TEST_REQUEST = "CREATE_TEST_REQUEST";
export const CREATE_TEST_SUCCESS = "CREATE_TEST_SUCCESS";
export const CREATE_TEST_FAIL = "CREATE_TEST_FAIL";

export const GET_ALL_DETAILS_REQUEST = "GET_ALL_DETAILS_REQUEST";
export const GET_ALL_DETAILS_SUCCESS = "GET_ALL_DETAILS_SUCCESS";
export const GET_ALL_DETAILS_FAIL = "GET_ALL_DETAILS_FAIL";
